import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import HomeContents from "./components/HomeContents"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fashion Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents />
    </div>
  )
}
